### PR TITLE
Update maintainer

### PR DESCRIPTION
**Pull request by Peter9606**
I'm so glad to be the "co-maintainer" of rqt_tf_tree project. Hope I can contribute the community while learning from @dirk-thomas, @130s and all other contributors.

### CODE REVIEW

**Comment by 130s** [comment]
@ros-pull-request-builder retest this please.

**Comment by Peter9606** [comment]
@130s  Is there something wrong with the Jenkins job? I cannot see the build that triggered by you request.

**Comment by 130s** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
@130s I don't think this repository has a pull request job enabled.

**Comment by 130s** [comment]
@ros-pull-request-builder retest this please

**Comment by Peter9606** [comment]
@130s are you sure there's a Jenkins job for this project?

**Comment by 130s** [comment]
Yeah, e.g. [Kinetic](https://github.com/ros/rosdistro/blob/6c82bef0951208ae1fb30f0f581c5da1876145af/kinetic/distribution.yaml#L6652), [Lunar](https://github.com/ros/rosdistro/blob/6c82bef0951208ae1fb30f0f581c5da1876145af/lunar/distribution.yaml#L2109), and I think pull request test is [enabled as wiki page instruction](http://wiki.ros.org/buildfarm/Pull%20request%20testing#Enable_pull_request_testing_for_a_specific_repository_on_Github). Let me try retriggering by close-reopen this PR.

**Comment by 130s** [comment]
@ros-pull-request-builder retest this please

**Comment by Peter9606** [comment]
Seems not work. Can anyone check with CI engineer ?

**Comment by 130s** [comment]
@Peter9606 sorry to have used this PR to check the testing feature but let us just continue figuring the issue.

@dirk-thomas sorry to bother you once more but as mentioned in https://github.com/ros-visualization/rqt_tf_tree/pull/3#issuecomment-299677353 I can't find anything missing in the PR testing setting. Could you take a look?

**Comment by Peter9606** [comment]
@130s  It's totally okay. I checked dist configuration seems it's correctly configured and have no idea why this doesn't work.

**Comment by dirk-thomas** [comment]
The @ros-pull-request-builder user was only a member of the org unit and had only admin access to a subset of repos. I changed the role to "owner" which will enable Jenkins to establish the webhook.

**Comment by 130s** [comment]
Thanks! I [added that info to wiki](http://wiki.ros.org/action/info/buildfarm/Pull%20request%20testing?action=diff&rev2=17&rev1=16).

Test passed (as we all knew it would ;) ).

**Pull request merged**
