### PR TITLE
Update maintainers

### PR DESCRIPTION
**Pull request by mabelzhang**
Signed-off-by: Mabel Zhang <mabel@openrobotics.org>

### CODE REVIEW

**Review by dirk-thomas — APPROVED** [review]

**Comment by dirk-thomas** [comment]
Note the failing PR build which should probably be retriggered.

**Comment by mabelzhang** [comment]
@ros-pull-request-builder retest this please

**Comment by mabelzhang** [comment]
Yay green now. Merging. Thanks!

**Comment by HAR0070** [comment]
Someone put a readme atleast. Please - will be helpful for noobs

**Comment by mabelzhang** [comment]
Hi @HAR0070, this is an old merged PR. Comments on PRs should be directly related to the PR. Please direct questions and requests to [ROS Answers](http://answers.ros.org/), where you will find a community already using this package and others.

This package is part of many rqt packages. You can find documentation about this package at
http://wiki.ros.org/rqt_tf_tree
and a tutorial at
http://wiki.ros.org/tf/Tutorials/Introduction%20to%20tf

**Pull request merged**
